"""Regenerate runtime WebP files and intrinsic dimensions; originals stay intact.
Requires cwebp and webpinfo from libwebp. Run from any directory with Python 3.
"""
import json
from pathlib import Path
import re
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/assets'


def dimensions(path):
    data = path.read_bytes()
    if data[:8] == b'\x89PNG\r\n\x1a\n':
        return struct.unpack('>II', data[16:24])
    if data[:2] == b'\xff\xd8':
        i = 2
        while i < len(data):
            if data[i] != 255:
                i += 1
                continue
            while data[i] == 255:
                i += 1
            marker = data[i]
            i += 1
            length = int.from_bytes(data[i:i+2], 'big')
            if marker in (0xc0, 0xc1, 0xc2):
                height, width = struct.unpack('>HH', data[i+3:i+7])
                return width, height
            i += length
    raise ValueError(f'Unsupported image dimensions: {path}')


report = []
entries = []
imports = []
for source in sorted(ASSETS.rglob('*')):
    if source.suffix not in ('.png', '.jpeg', '.jpg'):
        continue
    if source.parent.name == 'icons' and source.name != 'rec-map.png':
        continue
    limit = (1000 if source.name.startswith('dish-') else
             360 if source.parent.name == 'restaurants' else
             800 if source.parent.name == 'mascots' else
             1000 if source.name == 'welcome-background.png' else 600)
    width, height = dimensions(source)
    target_width = min(width, limit)
    target = source.with_suffix('.webp')
    subprocess.run(['cwebp', '-quiet', '-q', '85', '-m', '6', '-resize', str(target_width), '0', str(source), '-o', str(target)], check=True)
    # Read the actual encoder output dimensions rather than assuming its rounding.
    result = subprocess.run(['webpinfo', '-summary', str(target)], text=True, capture_output=True, check=True)
    actual_width = int(re.search(r'Width: (\d+)', result.stdout)[1])
    actual_height = int(re.search(r'Height: (\d+)', result.stdout)[1])
    name = f'image{len(entries)}'
    imports.append(f"import {name} from '../assets/{target.relative_to(ASSETS)}'")
    entries.append(f'  [{name}]: {{ width: {actual_width}, height: {actual_height} }},')
    report.append({'source': str(source.relative_to(ROOT)), 'runtime': str(target.relative_to(ROOT)), 'before': source.stat().st_size, 'after': target.stat().st_size})
(ROOT / 'src/data/imageDimensions.js').write_text('// Generated by scripts/optimize-images.py.\n' + '\n'.join(imports) + '\n\nexport const imageDimensions = {\n' + '\n'.join(entries) + '\n}\n')
print(json.dumps(report, indent=2))
